//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class billDetail
    {
        public int id { get; set; }
        public Nullable<int> idBill { get; set; }
        public Nullable<int> tourID { get; set; }
        public Nullable<int> pay { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> finish { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual tour tour { get; set; }
    }
}
