//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour()
        {
            this.billDetails = new HashSet<billDetail>();
            this.descriptionTours = new HashSet<descriptionTour>();
            this.tourDetails = new HashSet<tourDetail>();
            this.tourImgs = new HashSet<tourImg>();
        }
    
        public int tourID { get; set; }
        public Nullable<int> vacationID { get; set; }
        public string name { get; set; }
        [DisplayName("Start")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "{0} is required")]
        public Nullable<System.DateTime> start { get; set; }
        [DisplayName("Finish")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "{0} is required")]
        public Nullable<System.DateTime> finish { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<int> sales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billDetail> billDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<descriptionTour> descriptionTours { get; set; }
        public virtual vacation vacation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tourDetail> tourDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tourImg> tourImgs { get; set; }
    }
}
